###############################################################################
#
# Configuration for Microsoft NNI
# Reference: https://nni.readthedocs.io/en/latest/Tutorial/ExperimentConfig.html
#
# Launch the experiment:
# - replace the PROF_DIR and ENV_DIR with your own project and environment paths respectively.
# - configure the experiment (e.g. changing the duration, concurrency, and tuner etc.)
# - execute the following command: $ nnictl create --config ${PROJ_DIR}/exps/example/config.yaml --debug --port ${PROT_NUM}
#
###############################################################################

experimentName: "NNI example"
experimentWorkingDirectory: "${PROJ_DIR}/logs/nni"

maxExperimentDuration: 14d
maxTrialNumber: 1000
searchSpaceFile: "search_space.json"
useAnnotation: false

trialConcurrency: 1
trialGpuNumber: 4
trialCommand: PYTHONPATH="${PROJ_DIR}:${PYTHONPATH}" ${ENV_DIR}/bin/python ${PROJ_DIR}/exps/example/launcher.py
trialCodeDirectory: ${PROJ_DIR}/exps/example

tuner:
  name: TPE
  classArgs:
    optimize_mode: maximize

trainingService:
  platform: local
  useActiveGpu: true
