[comet]
api_key = 'gd2RifnioVchODAgpk637Br8f'
workspace = 'yacinebelhadj'
project_elia = 'PSM_elia'
project_elia_1 = 'PSM_elia_nperseg'

[local_comet]
path = '/home/yacine/Documents/PhD/Code/GitProject/PBSHM_mdof/experiment_logs_elia'
