[POPULATION]
    [POPULATION.TYPE1]
        [POPULATION.TYPE1.PARAM]
            m_mean = [0.5318, 0.4040, 0.4101, 0.4123, 0.3960, 0.3809, 0.4086, 0.3798]
            k_mean = [1e-3, 56700, 56700, 56700, 56700, 56700, 56700, 56700]
            c_mean = [8.746, 8.791, 8.801, 8.851, 8.714, 8.737, 8.549, 8.752]
            m_std = 0.03
            k_std = 0.01
            c_std = 0.08
        [POPULATION.TYPE1.INFO]
            N = 20
            N_dof = 8
    [POPULATION.INSTANCES]
        [POPULATION.INSTANCES.EX1]
        