[DATAELIA]
[DATAELIA.PATH]
raw = "/media/yacine/Intenso/RawData"
processed = "/home/yacine/Documents/PhD/Code/GitProject/PBSHM_mdof/data_elia/processed"
model = "/home/yacine/Documents/PhD/Code/GitProject/PBSHM_mdof/model/model_elia"

[DATAELIA.SENSOR]
fs = 250

[PROCESSING]
[PROCESSING.settings1]
nperseg=1024
filter_params={order=2,lpf=50}
duration = 10 # in minutes
step = 5 # in minutes

[NeuralNetwork]
[NeuralNetwork.settings1]
freq_range = [0, 50]

[MEASUREMENTS]
start = "2022-03-29 12:00:00"
end = "2022-06-25 00:06:00"

[EVENT]
[EVENT.start_measurements]
timestamp = "2022-03-29 12:00:00"
state = "healthy"
abbr = "training-test"
name ='training-test'
[EVENT.remove_bolt]
timestamp = "2022-04-25 08:05:00"
state = "damaged"
abbr = "a"
name ='remove_bolt'
[EVENT.incomplete_bolt]
timestamp = "2022-04-27 08:57:00"
state = "damaged"
abbr = "b"
name ='incomplete_bolt'
[EVENT.loose_bolt]
timestamp = "2022-04-29 09:22:00"
state = "damaged"
abbr = "c"
name ='loose_bolt'
[EVENT.tighten_bolt]
timestamp = "2022-05-03 08:35:00"
state = "healthy"
abbr = "d"
name ='tighten_bolt'
[EVENT.buckling_EW916]
timestamp = "2022-05-09 08:05:00"
state = "damaged"
abbr = "e"
name ='buckling_EW916'
[EVENT.removal_EW916]
timestamp = "2022-05-16 07:36:00"
state = "damaged"
abbr = "f"
name ='removal_EW916'
[EVENT.removal_EW918]
timestamp = "2022-05-23 12:04:00"
state = "damaged"
abbr = "g"
name ='removal_EW918'
[EVENT.replacement_EW916_918]
timestamp = "2022-05-30 06:51:00"
state = "healthy"
abbr = "h"
name ='replacement_EW916_918'
[EVENT.grinding_EW196]
timestamp = "2022-06-07 08:09:00"
state = "damaged"
abbr = "i"
name ='grinding_EW196'
[EVENT.Reinforcement_EW916]
timestamp = "2022-06-13 08:06:00"
state = "damaged"
abbr = "j"
name ='Reinforcement_EW916'

[STAGE]
[STAGE.training]
start = "2022-03-29 12:00:00"
end = "2022-04-20 00:00:00"
[STAGE.testing]
start = "2022-04-20 00:00:00"
end = "2022-04-25 08:05:00"
[STAGE.anomaly]
start = "2022-04-25 08:05:00"
end = "2022-06-25 08:06:00"

[ACTIVITY]
[ACTIVITY.climbing]
[ACTIVITY.climbing.start]
timestamp = "2022-06-07 07:59:00"
[ACTIVITY.climbing.end]
timestamp = "2022-06-07 08:06:00"
